### ISSUE TITLE
[BUG Report]: Runtime cannot load more recent CUDA .dll files

### ISSUE THREAD

**Issue by TheFirstDeity** [SciSharp/TensorFlow.NET#1288]
### Description

This library appears to use an old version of the CUDA toolkit libraries. The readme on this project doesn't document which release I need to install so that I can use this library with the GPU. It isn't apparent from the file names, or list of releases on [NVidia's archive](https://developer.nvidia.com/cuda-toolkit-archive) what version I need to install.

For example, one error indicates `Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found`. When I go into the install path under the environment variable CUDA_PATH that was set during installation there is a file `bin\cudart64_12.dll` (along with some others). It looks like it's checking for different versions of the same files.

I have the latest versions of CUDA toolkit, cuDNN, and NVidia drivers installed. All the libraries needed to run tensorflow should be there. If there's a specific version I need to download, please let me know. It should be documented in the Installation section of the readme.

### Reproduction Steps

- Made a new project and read out sample data.
- Installed the two most recent versions of CUDA toolkit (10 and 11) from: https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64

Example:
```
using keras = Tensorflow.Keras;
using Tensorflow.Keras.Datasets;

public class Brain
{
    public DatasetPass Dataset = new keras.Datasets.Mnist().load_data();
}
```
Then I displayed the data in another file: `infoLabel.Text = $"{nameof(Tensorflow.NumPy.NDArray)} = {brain.Dataset.Train.Item1}";`

Received the following error messages in the debugger:
```
2025-02-16 17:50:34.898721: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2025-02-16 17:50:34.899170: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
...
2025-02-16 17:50:35.145616: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-16 17:50:35.208050: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2025-02-16 17:50:35.209043: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2025-02-16 17:50:35.209730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2025-02-16 17:50:35.210525: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2025-02-16 17:50:45.067464: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2025-02-16 17:50:45.068052: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2025-02-16 17:50:45.068074: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

### Configuration and Other Information

```
<TargetFramework>net9.0</TargetFramework>
...
  <ItemGroup>
    <PackageReference Include="SciSharp.TensorFlow.Redist-Windows-GPU" Version="2.10.3" />
    <PackageReference Include="TensorFlow.Keras" Version="0.15.0" />
    <PackageReference Include="TensorFlow.NET" Version="0.150.0" />
  </ItemGroup>
```

**Comment by Tony-Pappas** [comment]
I was getting runtime error: _Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found_.

I installed `Microsoft.ML.TensorFlow.Redist` and the error went away.

Maybe that'll clean these up for you too...
